%  Auto-generated by MATLAB on 22-Apr-2022 17:03:20

% Create figure and calculate time in hours
figure1 = figure('InvertHardcopy','off','Color',[1 1 1]);
thours = tnew/3600;

% Create axes
axes1 = axes('Parent', figure1);
hold(axes1,'on');
colororder([0 0.447058823529412 0.741176470588235;0.466666666666667 0.674509803921569 0.188235294117647;0.929411764705882 0.694117647058824 0.125490196078431;0.650980392156863 0.650980392156863 0.650980392156863]);

% Create multiple lines using matrix input to plot
plot1 = plot(thours,graphCPARP,...
    'Parent',axes1);

% Create ylabel
ylabel('CPARP (molecules/cell)',...
    'HorizontalAlignment','center');

% Create xlabel
xlabel('Time (hrs)',...
    'HorizontalAlignment','center');

% Uncomment the following line to preserve the X-limits of the axes
% xlim(axes1,[0 24]);
% Uncomment the following line to preserve the Y-limits of the axes
ylim(axes1,[0 1000000]);
xlim(axes1,[0 24]);
hold(axes1,'off');
% Set the remaining axes properties
set(axes1,'FontName',...
    'Arial','FontSize',14,...
    'LineWidth',1,'TickDir',...
    'out','XTick',...
    [0 4 8 12 16 20 24]);
